repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.3.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: check-merge-conflict
  - id: check-case-conflict
  - id: check-symlinks
  - id: check-added-large-files
  - id: trailing-whitespace
  - id: pretty-format-json
    args: [--autofix]
  - id: end-of-file-fixer
- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 2.1.5
  hooks:
    - id: shellcheck
    - id: shfmt
- repo: https://github.com/IamTheFij/docker-pre-commit
  rev: 2.0.0
  hooks:
    - id: hadolint
