# action.yml
name: 'Automerge PR'
description: 'Automatically merge a PR if all the checks pass'
inputs:
  label:
    description: 'Label of the PR to check for automerge. If label is not set, no action will be taken'
    required: false
    default: 'automerge'
  GITHUB_TOKEN:
    description: 'Github token for contacting the API'
    required: true
  JOB:
    default: ${{ job }}
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.label }}
