on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: dog food
      uses: mhristof/github-action-automerge@master
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
