on: [push]

jobs:
  wait:
    runs-on: ubuntu-latest
    name: sleep
    steps:
      - run: sleep 25s
  hello_world_job:
    runs-on: ubuntu-latest
    name: dogfood
    steps:
    - name: dog food
      uses: mhristof/github-action-automerge@setup-auth
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        JOB_CONTEXT: ${{ toJSON(job) }}
