on: [push]

jobs:
  goodJob:
    runs-on: ubuntu-latest
    name: good job
    steps:
      - run: /bin/true
  wait:
    runs-on: ubuntu-latest
    name: sleep
    steps:
      - run: sleep 25s
  hello_world_job:
    runs-on: ubuntu-latest
    name: automerge
    steps:
    - name: dog food
      uses: mhristof/github-action-automerge@${GITHUB_REF##*/}
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
