on: [push]

jobs:
  goodJob:
    runs-on: ubuntu-latest
    name: good job
    steps:
      - run: /bin/true
  wait:
    runs-on: ubuntu-latest
    name: sleep
    steps:
      - run: sleep 25s
  hello_world_job:
    runs-on: ubuntu-latest
    name: automerge
    steps:
      - name: dog food (this branch)
        uses: mhristof/github-action-automerge@dont-fail-on-a-non-pr-build # THIS BRANCH
        if: github.ref != 'refs/heads/main'
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: dog food (main)
        uses: mhristof/github-action-automerge@main
        if: github.ref == 'refs/heads/main'
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
