on: [push]

jobs:
  goodJob:
    runs-on: ubuntu-latest
    name: good job
    steps:
      - run: /bin/true
  wait:
    runs-on: ubuntu-latest
    name: sleep
    steps:
      - run: sleep 25s
  hello_world_job:
    runs-on: ubuntu-latest
    name: automerge
    steps:
      - name: Set branch
        id: branch
        run: echo '::set-output name=BRANCH::${GITHUB_REF##*/}'
      - run: echo ${{ steps.branch.outputs.BRANCH }}
      - name: dog food
        uses: mhristof/github-action-automerge@${{ steps.branch.outputs.BRANCH }}
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
