
name: precommit

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install precommit
        run: pip install pre-commit
      - name: run pre-commit
        run: pre-commit run --all-files
